version: '3.8'

services:
  db:
    image: postgres:15
    container_name: devevents-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: devevents_db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: devevents-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db