spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/devevents_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Desativar segurança básica inicialmente para podermos testar o setup
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration